# Generated by Django 2.2.4 on 2019-08-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='sharing',
            field=models.ManyToManyField(to='dashboard.SharingModel'),
        ),
    ]
