# Generated by Django 2.2.4 on 2019-08-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_notemodel_sharing'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
