# Generated by Django 2.2.4 on 2019-08-11 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_notemodel_shared'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notemodel',
            old_name='sharing',
            new_name='shared_users',
        ),
    ]
