# Generated by Django 2.2.4 on 2019-08-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190811_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharingmodel',
            name='read',
            field=models.BooleanField(default=True),
        ),
    ]
