# Generated by Django 2.2.4 on 2019-08-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190811_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
