# Generated by Django 2.2.4 on 2019-08-12 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20190811_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notemodel',
            old_name='shared_users',
            new_name='sharing',
        ),
    ]
